FROM debian:bookworm

RUN apt-get update && \
  apt-get install -y --no-install-recommends curl ca-certificates libdav1d-dev libclang-dev build-essential pkg-config git
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - &&\
  apt-get install -y nodejs &&\
  corepack enable
