name: Release

on:
  release:
    types: [published]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download build
        uses: dawidd6/action-download-artifact@v2.27.0
        with:
          workflow: ci.yml
          commit: ${{ github.sha }}
          name: union_bug-server
          path: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push container image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/nbudin/union_bug:${{ github.event.release.name }}
            ghcr.io/nbudin/union_bug:latest
