name: Release

on:
  release:
    types: [published]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Build and push container image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ghcr.io/nbudin/union_bug:${{ github.event.release.name }}
